# Generated by Django 3.2.4 on 2021-12-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
