# Generated by Django 3.2.4 on 2021-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_entrada_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
