# Generated by Django 3.2.4 on 2021-12-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_entrada_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
